// Re-export all schemas
export * from './doctors';
export * from './patients';
export * from './registrations';
export * from './medical-history';
export * from './vital-signs';
export * from './examinations';
export * from './recommendations';
export * from './treating-doctors';
export * from './comments';
